# -*- coding: utf-8 -*-
"""prompt_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXN-lY21ZPQIxPvBc23YyCyo_92gB5ZF
"""

def create_deepui_prompt(role, rules, actions, semantic_descriptions):
    prompt = f"""Role: {role}

Rules: {rules}

Operating Actions on the App: {actions}

Annotated Screenshots:
{semantic_descriptions}

Please identify any logical or UI bugs in the above scenario. If no issues are detected, respond with "No error"."""
    return prompt