# -*- coding: utf-8 -*-
"""Textprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAhrw_ZmN35Mmnyr6jM6wUlDpu5F6O5X
"""

class TextProcessing:
    def __init__(self, chatgpt4_config):
        self.chatgpt4_config = chatgpt4_config

    def generate_output_for_prompt(self, prompt):
        return self.chatgpt4_config.get_chatgpt4_response(prompt)